import { constants, type PathLike } from "node:fs";
import {
  link,
  lstat,
  mkdir,
  mkdtemp,
  open,
  readFile,
  readdir,
  realpath,
  rename,
  rm,
  utimes,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, join } from "node:path";
import { afterEach, expect, test, vi } from "vitest";

const race = vi.hoisted(() => ({
  recoveryPath: "",
  onRecoveryOpen: undefined as (() => Promise<void>) | undefined,
  onStageOpen: undefined as (() => Promise<void>) | undefined,
  onStageWrite: undefined as (() => Promise<void>) | undefined,
  onPublishLink: undefined as (() => Promise<void>) | undefined,
  onPublishRename: undefined as (() => Promise<void>) | undefined,
  stagePath: "",
  stageFlags: 0,
  stageMode: 0,
}));

vi.mock("node:fs/promises", async (importOriginal) => {
  const actual = await importOriginal<typeof import("node:fs/promises")>();
  return {
    ...actual,
    open: async (path: PathLike, flags: string | number, mode?: number) => {
      const handle = await actual.open(path, flags, mode);
      if (String(path) === race.recoveryPath) {
        const onOpen = race.onRecoveryOpen;
        race.onRecoveryOpen = undefined;
        await onOpen?.();
      }
      if (basename(String(path)).startsWith(".eai-write-")) {
        race.stagePath = String(path);
        race.stageFlags = Number(flags);
        race.stageMode = Number(mode);
        const onOpen = race.onStageOpen;
        race.onStageOpen = undefined;
        await onOpen?.();
        const originalWrite = handle.writeFile.bind(handle);
        handle.writeFile = (async (...args: Parameters<typeof handle.writeFile>) => {
          const onWrite = race.onStageWrite;
          race.onStageWrite = undefined;
          await onWrite?.();
          return originalWrite(...args);
        }) as typeof handle.writeFile;
      }
      return handle;
    },
    rename: async (oldPath: PathLike, newPath: PathLike) => {
      if (basename(String(oldPath)).startsWith(".eai-write-")) {
        const onRename = race.onPublishRename;
        race.onPublishRename = undefined;
        await onRename?.();
      }
      return actual.rename(oldPath, newPath);
    },
    link: async (existingPath: PathLike, newPath: PathLike) => {
      if (basename(String(existingPath)).startsWith(".eai-write-")) {
        const onLink = race.onPublishLink;
        race.onPublishLink = undefined;
        await onLink?.();
      }
      return actual.link(existingPath, newPath);
    },
  };
});

import {
  writeBoundRegularFile,
  writePrivateFileNoFollow,
} from "../../src/lib/eai-managed-deploy-filesystem.js";
import { prepareManagedDeployStateDirectory } from "../../src/lib/eai-managed-deploy-state.js";
import { bindManagedProjectRoot } from "../../src/lib/eai-managed-root-binding.js";

const cleanup: string[] = [];
const original = "original authorized bytes\n";
const replacement = "unrelated replacement bytes\n";
const updated = "new generated bytes\n";
const writers = [
  { name: "generated", mode: 0o644, write: writeBoundRegularFile },
  {
    name: "private",
    mode: 0o600,
    write: (path: string, content: string, _mode: number, binding?: Awaited<ReturnType<typeof bindManagedProjectRoot>>) =>
      writePrivateFileNoFollow(path, content, binding),
  },
];

afterEach(async () => {
  race.recoveryPath = "";
  race.onRecoveryOpen = undefined;
  race.onStageOpen = undefined;
  race.onStageWrite = undefined;
  race.onPublishLink = undefined;
  race.onPublishRename = undefined;
  race.stagePath = "";
  race.stageFlags = 0;
  race.stageMode = 0;
  await Promise.all(cleanup.splice(0).map(path => rm(path, { recursive: true, force: true })));
});

test("recovery permissions never modify a directory substituted after descriptor opening", async () => {
  const work = await realpath(await mkdtemp(join(tmpdir(), "managed-recovery-permission-race-")));
  cleanup.push(work);
  const recovery = join(work, "recovery");
  const previous = join(work, "original-recovery");
  await mkdir(recovery, { mode: 0o750 });
  race.recoveryPath = recovery;
  race.onRecoveryOpen = async () => {
    await rename(recovery, previous);
    await mkdir(recovery, { mode: 0o750 });
  };
  await expect(prepareManagedDeployStateDirectory(recovery)).rejects.toThrow("changed before permission update");
  expect((await lstat(recovery)).mode & 0o777).toBe(0o750);
  expect((await lstat(previous)).mode & 0o777).toBe(0o750);
});

async function fixture(mode: number): Promise<{ work: string; root: string; parent: string; target: string }> {
  const work = await realpath(await mkdtemp(join(tmpdir(), "managed-atomic-write-")));
  cleanup.push(work);
  const root = join(work, "app");
  const parent = join(root, "output");
  await mkdir(parent, { recursive: true, mode: 0o700 });
  const target = join(parent, "output.json");
  await writeFile(target, original, { mode });
  return { work, root, parent, target };
}

test.each(writers)("$name publishes a new inode without modifying an existing opened file", async writer => {
  const { root, parent, target } = await fixture(writer.mode);
  const previous = await open(target, constants.O_RDONLY);
  const before = await previous.stat();
  try {
    await writer.write(target, updated, writer.mode, await bindManagedProjectRoot(root));
    expect(await previous.readFile("utf8")).toBe(original);
    expect(await readFile(target, "utf8")).toBe(updated);
    const accepted = await lstat(target);
    expect(accepted.ino).not.toBe(before.ino);
    expect(accepted.nlink).toBe(1);
    expect(accepted.mode & 0o777).toBe(writer.mode);
    expect(race.stageMode).toBe(0o600);
    for (const flag of [constants.O_EXCL, constants.O_NOFOLLOW, constants.O_NONBLOCK]) {
      expect(race.stageFlags & flag).not.toBe(0);
    }
    expect(await readdir(parent)).toEqual(["output.json"]);
  } finally {
    await previous.close();
  }
});

test.each(writers)("$name preserves both existing files when the parent moves after the write guard", async writer => {
  const { work, root, parent, target } = await fixture(writer.mode);
  const displaced = join(work, "moved-original-parent");
  const attacker = join(work, "replacement-parent");
  await mkdir(attacker, { mode: 0o700 });
  await writeFile(join(attacker, "output.json"), replacement, { mode: writer.mode });
  race.onStageWrite = async () => {
    await rename(parent, displaced);
    await rename(attacker, parent);
  };
  await expect(writer.write(target, updated, writer.mode, await bindManagedProjectRoot(root)))
    .rejects.toThrow("evidence directory changed");
  expect(await readFile(join(displaced, "output.json"), "utf8")).toBe(original);
  expect(await readFile(target, "utf8")).toBe(replacement);
  const abandonedStage = join(displaced, basename(race.stagePath));
  expect((await lstat(abandonedStage)).mode & 0o777).toBe(0o600);
});

test.each(writers)("$name preserves both existing files when the project root moves during staging", async writer => {
  const { work, root, target } = await fixture(writer.mode);
  const displaced = join(work, "moved-original-root");
  const attacker = join(work, "replacement-root");
  await mkdir(join(attacker, "output"), { recursive: true, mode: 0o700 });
  await writeFile(join(attacker, "output/output.json"), replacement, { mode: writer.mode });
  race.onStageWrite = async () => {
    await rename(root, displaced);
    await rename(attacker, root);
  };
  await expect(writer.write(target, updated, writer.mode, await bindManagedProjectRoot(root)))
    .rejects.toThrow(/(?:project root|evidence directory) changed/);
  expect(await readFile(join(displaced, "output/output.json"), "utf8")).toBe(original);
  expect(await readFile(target, "utf8")).toBe(replacement);
});

test.each(writers)("$name does not remove an attacker replacement staging leaf on rejection", async writer => {
  const { parent, target } = await fixture(writer.mode);
  race.onStageWrite = async () => {
    await rename(race.stagePath, join(parent, "displaced-stage"));
    await writeFile(race.stagePath, replacement, { mode: 0o600 });
  };
  await expect(writer.write(target, updated, writer.mode)).rejects.toThrow("untrusted file");
  expect(await readFile(target, "utf8")).toBe(original);
  expect(await readFile(race.stagePath, "utf8")).toBe(replacement);
});

test.each(writers)("$name rejects a hard-linked existing target without changing either link", async writer => {
  const { parent, target } = await fixture(writer.mode);
  const alias = join(parent, "target-alias");
  await link(target, alias);
  await expect(writer.write(target, updated, writer.mode)).rejects.toThrow("untrusted file");
  expect(await readFile(target, "utf8")).toBe(original);
  expect(await readFile(alias, "utf8")).toBe(original);
});

test.each(writers)("$name rejects a stage linked before validation without writing through either link", async writer => {
  const { parent, target } = await fixture(writer.mode);
  const alias = join(parent, "stage-alias");
  race.onStageOpen = async () => { await link(race.stagePath, alias); };
  await expect(writer.write(target, updated, writer.mode)).rejects.toThrow("untrusted file");
  expect(await readFile(target, "utf8")).toBe(original);
  expect(await readFile(alias, "utf8")).toBe("");
});

test.each(writers)("$name preserves a concurrent edit made during staging", async writer => {
  const { parent, target } = await fixture(writer.mode);
  race.onStageWrite = async () => { await writeFile(target, replacement); };
  await expect(writer.write(target, updated, writer.mode)).rejects.toThrow("file changed before its bound write");
  expect(await readFile(target, "utf8")).toBe(replacement);
  expect(await readdir(parent)).toEqual(["output.json"]);
});

test.each(writers)("$name publishes an inspected-absent target exclusively and removes its staging link", async writer => {
  const { root, parent, target } = await fixture(writer.mode);
  await rm(target);
  await writer.write(target, updated, writer.mode, await bindManagedProjectRoot(root));
  expect(await readFile(target, "utf8")).toBe(updated);
  const accepted = await lstat(target);
  expect(accepted.mode & 0o777).toBe(writer.mode);
  expect(accepted.nlink).toBe(1);
  expect(await readdir(parent)).toEqual(["output.json"]);
});

test.each(writers)("$name cannot overwrite a target appearing at exclusive publication", async writer => {
  const { parent, target } = await fixture(writer.mode);
  await rm(target);
  race.onPublishLink = async () => { await writeFile(target, replacement, { mode: writer.mode }); };
  await expect(writer.write(target, updated, writer.mode)).rejects.toMatchObject({ code: "EEXIST" });
  expect(await readFile(target, "utf8")).toBe(replacement);
  expect(await readdir(parent)).toEqual(["output.json"]);
});


test.each(writers)("$name rejects a same-size staging rewrite during publication", async writer => {
  const { target } = await fixture(writer.mode);
  const previous = await open(target, constants.O_RDONLY);
  try {
    race.onPublishRename = async () => {
      const before = await lstat(race.stagePath);
      await writeFile(race.stagePath, "x".repeat(Buffer.byteLength(updated)));
      await utimes(race.stagePath, before.atime, new Date(before.mtimeMs + 1000));
    };
    await expect(writer.write(target, updated, writer.mode)).rejects.toThrow("published file changed");
    expect(await previous.readFile("utf8")).toBe(original);
  } finally {
    await previous.close();
  }
});
